<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="LAPTOP-HUA8CH3G" name="TC_001_Requests" tests="5" failures="0" timestamp="2021-01-12T19:14:51 IST" time="0.031" errors="1">
  <testcase name="test_Get" time="0.031" classname="TC_001_Requests">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method TC_001_Requests.test_Get() didn&#039;t finish within the time-out 10">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TC_001_Requests.test_Get() didn't finish within the time-out 10
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:371)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:282)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:605)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- test_Get -->
  <system-out/>
  <testcase name="test_Post" classname="TC_001_Requests">
    <skipped/>
  </testcase> <!-- test_Post -->
  <system-out/>
  <testcase name="test_Patch" classname="TC_001_Requests">
    <skipped/>
  </testcase> <!-- test_Patch -->
  <system-out/>
  <testcase name="test_Put" classname="TC_001_Requests">
    <skipped/>
  </testcase> <!-- test_Put -->
  <system-out/>
  <testcase name="Delet" classname="TC_001_Requests">
    <skipped/>
  </testcase> <!-- Delet -->
  <system-out/>
</testsuite> <!-- TC_001_Requests -->
